/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileMetadata = IDL.Record({
  'path' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
});
export const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HeaderField),
});
export const StreamingToken = IDL.Record({
  'resource' : IDL.Text,
  'index' : IDL.Nat,
});
export const StreamingCallbackHttpResponse = IDL.Record({
  'token' : IDL.Opt(StreamingToken),
  'body' : IDL.Vec(IDL.Nat8),
});
export const StreamingCallback = IDL.Func(
    [StreamingToken],
    [StreamingCallbackHttpResponse],
    ['query'],
  );
export const StreamingStrategy = IDL.Variant({
  'Callback' : IDL.Record({
    'token' : StreamingToken,
    'callback' : StreamingCallback,
  }),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HeaderField),
  'streaming_strategy' : IDL.Opt(StreamingStrategy),
  'status_code' : IDL.Nat16,
});
export const MarketingInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const BirthdayPackage = IDL.Record({
  'id' : IDL.Text,
  'additionalChildPrice' : IDL.Nat,
  'socksIncluded' : IDL.Nat,
  'weekendPrice' : IDL.Nat,
  'weekdayPrice' : IDL.Nat,
  'name' : IDL.Text,
  'includedChildren' : IDL.Nat,
  'description' : IDL.Text,
  'roomTime' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Child = IDL.Record({
  'name' : IDL.Text,
  'birthday' : IDL.Opt(IDL.Text),
});
export const UnifiedWaiverForm = IDL.Record({
  'id' : IDL.Text,
  'parentEmail' : IDL.Text,
  'agreeUnifiedTerms' : IDL.Bool,
  'visitCount' : IDL.Nat,
  'parentPhone' : IDL.Text,
  'children' : IDL.Vec(Child),
  'termsAndConditions' : IDL.Text,
  'timestamp' : IDL.Int,
  'parentName' : IDL.Text,
});
export const CommunityPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'numChildren' : IDL.Nat,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'eventDate' : IDL.Text,
});
export const Time = IDL.Int;
export const EmailSubscriber = IDL.Record({
  'email' : IDL.Text,
  'timestamp' : Time,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'review' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const WebsiteContent = IDL.Record({
  'homepageText' : IDL.Text,
  'contactInfo' : IDL.Text,
  'aboutText' : IDL.Text,
  'operatingHours' : IDL.Text,
});
export const TranslationEntry = IDL.Record({
  'originalText' : IDL.Text,
  'translatedText' : IDL.Text,
});
export const LanguagePreference = IDL.Record({
  'userId' : IDL.Principal,
  'language' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBirthdayPackage' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addCommunityPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addGalleryImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOrUpdateTranslation' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkInWaiver' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'exportEmailSubscribersCSV' : IDL.Func([], [IDL.Text], ['query']),
  'fileDelete' : IDL.Func([IDL.Text], [], []),
  'fileList' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'fileRequest' : IDL.Func([HttpRequest], [HttpResponse], []),
  'fileUpload' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Bool],
      [],
      [],
    ),
  'getAllMarketingInfo' : IDL.Func([], [IDL.Vec(MarketingInfo)], ['query']),
  'getBirthdayPackages' : IDL.Func([], [IDL.Vec(BirthdayPackage)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckInStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'frequentVisitors' : IDL.Vec(UnifiedWaiverForm),
          'totalCheckIns' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getEmailSubscribers' : IDL.Func([], [IDL.Vec(EmailSubscriber)], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getLanguagePreference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getNewWaivers' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(UnifiedWaiverForm)],
      ['query'],
    ),
  'getPredefinedGalleryImages' : IDL.Func(
      [],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'getRecentWaivers' : IDL.Func([], [IDL.Vec(UnifiedWaiverForm)], ['query']),
  'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTotalCheckIns' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTranslation' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaiversWithVisitCounts' : IDL.Func(
      [],
      [IDL.Vec(UnifiedWaiverForm)],
      ['query'],
    ),
  'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
  'httpStreamingCallback' : IDL.Func(
      [StreamingToken],
      [StreamingCallbackHttpResponse],
      ['query'],
    ),
  'importTranslations' : IDL.Func([IDL.Vec(TranslationEntry)], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllWaivers' : IDL.Func([], [IDL.Vec(UnifiedWaiverForm)], ['query']),
  'listLanguagePreferences' : IDL.Func(
      [],
      [IDL.Vec(LanguagePreference)],
      ['query'],
    ),
  'listTranslations' : IDL.Func([], [IDL.Vec(TranslationEntry)], ['query']),
  'removeBirthdayPackage' : IDL.Func([IDL.Text], [], []),
  'removeCommunityPost' : IDL.Func([IDL.Text], [], []),
  'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
  'removeLanguagePreference' : IDL.Func([], [], []),
  'removeTestimonial' : IDL.Func([IDL.Text], [], []),
  'resetAdminAccess' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchWaivers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UnifiedWaiverForm)],
      ['query'],
    ),
  'setLanguagePreference' : IDL.Func([IDL.Text], [], []),
  'submitUnifiedWaiver' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Child), IDL.Bool, IDL.Text],
      [IDL.Text],
      [],
    ),
  'subscribeEmail' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'unifiedWaiverSearch' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UnifiedWaiverForm)],
      ['query'],
    ),
  'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileMetadata = IDL.Record({
    'path' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
  });
  const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
  });
  const StreamingToken = IDL.Record({
    'resource' : IDL.Text,
    'index' : IDL.Nat,
  });
  const StreamingCallbackHttpResponse = IDL.Record({
    'token' : IDL.Opt(StreamingToken),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const StreamingCallback = IDL.Func(
      [StreamingToken],
      [StreamingCallbackHttpResponse],
      ['query'],
    );
  const StreamingStrategy = IDL.Variant({
    'Callback' : IDL.Record({
      'token' : StreamingToken,
      'callback' : StreamingCallback,
    }),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
    'streaming_strategy' : IDL.Opt(StreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  const MarketingInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const BirthdayPackage = IDL.Record({
    'id' : IDL.Text,
    'additionalChildPrice' : IDL.Nat,
    'socksIncluded' : IDL.Nat,
    'weekendPrice' : IDL.Nat,
    'weekdayPrice' : IDL.Nat,
    'name' : IDL.Text,
    'includedChildren' : IDL.Nat,
    'description' : IDL.Text,
    'roomTime' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Child = IDL.Record({
    'name' : IDL.Text,
    'birthday' : IDL.Opt(IDL.Text),
  });
  const UnifiedWaiverForm = IDL.Record({
    'id' : IDL.Text,
    'parentEmail' : IDL.Text,
    'agreeUnifiedTerms' : IDL.Bool,
    'visitCount' : IDL.Nat,
    'parentPhone' : IDL.Text,
    'children' : IDL.Vec(Child),
    'termsAndConditions' : IDL.Text,
    'timestamp' : IDL.Int,
    'parentName' : IDL.Text,
  });
  const CommunityPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'numChildren' : IDL.Nat,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  const Time = IDL.Int;
  const EmailSubscriber = IDL.Record({
    'email' : IDL.Text,
    'timestamp' : Time,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'review' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const WebsiteContent = IDL.Record({
    'homepageText' : IDL.Text,
    'contactInfo' : IDL.Text,
    'aboutText' : IDL.Text,
    'operatingHours' : IDL.Text,
  });
  const TranslationEntry = IDL.Record({
    'originalText' : IDL.Text,
    'translatedText' : IDL.Text,
  });
  const LanguagePreference = IDL.Record({
    'userId' : IDL.Principal,
    'language' : IDL.Text,
  });
  
  return IDL.Service({
    'addBirthdayPackage' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addCommunityPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addGalleryImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOrUpdateTranslation' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkInWaiver' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'exportEmailSubscribersCSV' : IDL.Func([], [IDL.Text], ['query']),
    'fileDelete' : IDL.Func([IDL.Text], [], []),
    'fileList' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'fileRequest' : IDL.Func([HttpRequest], [HttpResponse], []),
    'fileUpload' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Bool],
        [],
        [],
      ),
    'getAllMarketingInfo' : IDL.Func([], [IDL.Vec(MarketingInfo)], ['query']),
    'getBirthdayPackages' : IDL.Func([], [IDL.Vec(BirthdayPackage)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckInStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'frequentVisitors' : IDL.Vec(UnifiedWaiverForm),
            'totalCheckIns' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getEmailSubscribers' : IDL.Func([], [IDL.Vec(EmailSubscriber)], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getLanguagePreference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getNewWaivers' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(UnifiedWaiverForm)],
        ['query'],
      ),
    'getPredefinedGalleryImages' : IDL.Func(
        [],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'getRecentWaivers' : IDL.Func([], [IDL.Vec(UnifiedWaiverForm)], ['query']),
    'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTotalCheckIns' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTranslation' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaiversWithVisitCounts' : IDL.Func(
        [],
        [IDL.Vec(UnifiedWaiverForm)],
        ['query'],
      ),
    'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
    'httpStreamingCallback' : IDL.Func(
        [StreamingToken],
        [StreamingCallbackHttpResponse],
        ['query'],
      ),
    'importTranslations' : IDL.Func([IDL.Vec(TranslationEntry)], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllWaivers' : IDL.Func([], [IDL.Vec(UnifiedWaiverForm)], ['query']),
    'listLanguagePreferences' : IDL.Func(
        [],
        [IDL.Vec(LanguagePreference)],
        ['query'],
      ),
    'listTranslations' : IDL.Func([], [IDL.Vec(TranslationEntry)], ['query']),
    'removeBirthdayPackage' : IDL.Func([IDL.Text], [], []),
    'removeCommunityPost' : IDL.Func([IDL.Text], [], []),
    'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
    'removeLanguagePreference' : IDL.Func([], [], []),
    'removeTestimonial' : IDL.Func([IDL.Text], [], []),
    'resetAdminAccess' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchWaivers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UnifiedWaiverForm)],
        ['query'],
      ),
    'setLanguagePreference' : IDL.Func([IDL.Text], [], []),
    'submitUnifiedWaiver' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Child), IDL.Bool, IDL.Text],
        [IDL.Text],
        [],
      ),
    'subscribeEmail' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'unifiedWaiverSearch' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UnifiedWaiverForm)],
        ['query'],
      ),
    'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };