/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type HeaderField = [string, string];
export interface EmailSubscriber {
    email: string;
    timestamp: Time;
}
export type Time = bigint;
export interface FileMetadata {
    path: string;
    size: bigint;
    mimeType: string;
}
export interface ContactSubmission {
    id: string;
    name: string;
    numChildren: bigint;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
    eventDate: string;
}
export interface StreamingToken {
    resource: string;
    index: bigint;
}
export interface StreamingCallbackHttpResponse {
    token?: StreamingToken;
    body: Uint8Array;
}
export type StreamingCallback = (arg0: StreamingToken) => Promise<StreamingCallbackHttpResponse>;
export interface TranslationEntry {
    originalText: string;
    translatedText: string;
}
export interface CommunityPost {
    id: string;
    title: string;
    content: string;
    author: string;
    timestamp: bigint;
}
export type StreamingStrategy = {
    __kind__: "Callback";
    Callback: {
        token: StreamingToken;
        callback: [Principal, string];
    };
};
export interface Child {
    name: string;
    birthday?: string;
}
export interface GalleryImage {
    id: string;
    url: string;
    description: string;
    timestamp: bigint;
}
export interface HttpResponse {
    body: Uint8Array;
    headers: Array<HeaderField>;
    streaming_strategy?: StreamingStrategy;
    status_code: number;
}
export interface UnifiedWaiverForm {
    id: string;
    parentEmail: string;
    agreeUnifiedTerms: boolean;
    visitCount: bigint;
    parentPhone: string;
    children: Array<Child>;
    termsAndConditions: string;
    timestamp: bigint;
    parentName: string;
}
export interface BirthdayPackage {
    id: string;
    additionalChildPrice: bigint;
    socksIncluded: bigint;
    weekendPrice: bigint;
    weekdayPrice: bigint;
    name: string;
    includedChildren: bigint;
    description: string;
    roomTime: string;
}
export interface LanguagePreference {
    userId: Principal;
    language: string;
}
export interface MarketingInfo {
    name: string;
    email: string;
    timestamp: bigint;
    phone: string;
}
export interface WebsiteContent {
    homepageText: string;
    contactInfo: string;
    aboutText: string;
    operatingHours: string;
}
export interface HttpRequest {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<HeaderField>;
}
export interface UserProfile {
    name: string;
}
export interface Testimonial {
    id: string;
    customerName: string;
    review: string;
    timestamp: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addBirthdayPackage(name: string, weekdayPrice: bigint, weekendPrice: bigint, includedChildren: bigint, additionalChildPrice: bigint, socksIncluded: bigint, roomTime: string, description: string): Promise<void>;
    addCommunityPost(title: string, content: string, author: string): Promise<void>;
    addContactSubmission(name: string, email: string, phone: string, eventDate: string, numChildren: bigint, message: string): Promise<void>;
    addGalleryImage(url: string, description: string): Promise<void>;
    addOrUpdateTranslation(originalText: string, translatedText: string): Promise<void>;
    addTestimonial(customerName: string, review: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkInWaiver(waiverId: string): Promise<bigint>;
    exportEmailSubscribersCSV(): Promise<string>;
    fileDelete(path: string): Promise<void>;
    fileList(): Promise<Array<FileMetadata>>;
    fileRequest(request: HttpRequest): Promise<HttpResponse>;
    fileUpload(path: string, contentType: string, content: Uint8Array, complete: boolean): Promise<void>;
    getAllMarketingInfo(): Promise<Array<MarketingInfo>>;
    getBirthdayPackages(): Promise<Array<BirthdayPackage>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCheckInStats(): Promise<{
        frequentVisitors: Array<UnifiedWaiverForm>;
        totalCheckIns: bigint;
    }>;
    getCommunityPosts(): Promise<Array<CommunityPost>>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getEmailSubscribers(): Promise<Array<EmailSubscriber>>;
    getGalleryImages(): Promise<Array<GalleryImage>>;
    getLanguagePreference(): Promise<string | null>;
    getNewWaivers(sinceTimestamp: bigint): Promise<Array<UnifiedWaiverForm>>;
    getPredefinedGalleryImages(): Promise<Array<GalleryImage>>;
    getRecentWaivers(): Promise<Array<UnifiedWaiverForm>>;
    getSubscriberCount(): Promise<bigint>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getTotalCheckIns(waiverId: string): Promise<bigint>;
    getTranslation(originalText: string): Promise<string | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWaiversWithVisitCounts(): Promise<Array<UnifiedWaiverForm>>;
    getWebsiteContent(): Promise<WebsiteContent>;
    httpStreamingCallback(token: StreamingToken): Promise<StreamingCallbackHttpResponse>;
    importTranslations(entries: Array<TranslationEntry>): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listAllWaivers(): Promise<Array<UnifiedWaiverForm>>;
    listLanguagePreferences(): Promise<Array<LanguagePreference>>;
    listTranslations(): Promise<Array<TranslationEntry>>;
    removeBirthdayPackage(id: string): Promise<void>;
    removeCommunityPost(id: string): Promise<void>;
    removeGalleryImage(id: string): Promise<void>;
    removeLanguagePreference(): Promise<void>;
    removeTestimonial(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchWaivers(searchTerm: string): Promise<Array<UnifiedWaiverForm>>;
    setLanguagePreference(language: string): Promise<void>;
    submitUnifiedWaiver(parentName: string, parentEmail: string, parentPhone: string, children: Array<Child>, agreeUnifiedTerms: boolean, termsAndConditions: string): Promise<string>;
    subscribeEmail(email: string): Promise<boolean>;
    unifiedWaiverSearch(searchTerm: string): Promise<Array<UnifiedWaiverForm>>;
    updateWebsiteContent(content: WebsiteContent): Promise<void>;
}
import type { Child as _Child, HeaderField as _HeaderField, HttpResponse as _HttpResponse, StreamingCallbackHttpResponse as _StreamingCallbackHttpResponse, StreamingStrategy as _StreamingStrategy, StreamingToken as _StreamingToken, UnifiedWaiverForm as _UnifiedWaiverForm, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBirthdayPackage(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBirthdayPackage(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBirthdayPackage(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addCommunityPost(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommunityPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommunityPost(arg0, arg1, arg2);
            return result;
        }
    }
    async addContactSubmission(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContactSubmission(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContactSubmission(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addGalleryImage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateTranslation(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateTranslation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateTranslation(arg0, arg1);
            return result;
        }
    }
    async addTestimonial(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async checkInWaiver(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInWaiver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInWaiver(arg0);
            return result;
        }
    }
    async exportEmailSubscribersCSV(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportEmailSubscribersCSV();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportEmailSubscribersCSV();
            return result;
        }
    }
    async fileDelete(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fileDelete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fileDelete(arg0);
            return result;
        }
    }
    async fileList(): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.fileList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fileList();
            return result;
        }
    }
    async fileRequest(arg0: HttpRequest): Promise<HttpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.fileRequest(arg0);
                return from_candid_HttpResponse_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fileRequest(arg0);
            return from_candid_HttpResponse_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async fileUpload(arg0: string, arg1: string, arg2: Uint8Array, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fileUpload(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fileUpload(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllMarketingInfo(): Promise<Array<MarketingInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketingInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketingInfo();
            return result;
        }
    }
    async getBirthdayPackages(): Promise<Array<BirthdayPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBirthdayPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBirthdayPackages();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCheckInStats(): Promise<{
        frequentVisitors: Array<UnifiedWaiverForm>;
        totalCheckIns: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInStats();
                return from_candid_record_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInStats();
            return from_candid_record_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCommunityPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityPosts();
            return result;
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getEmailSubscribers(): Promise<Array<EmailSubscriber>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailSubscribers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailSubscribers();
            return result;
        }
    }
    async getGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImages();
            return result;
        }
    }
    async getLanguagePreference(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLanguagePreference();
                return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLanguagePreference();
            return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getNewWaivers(arg0: bigint): Promise<Array<UnifiedWaiverForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewWaivers(arg0);
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewWaivers(arg0);
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPredefinedGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredefinedGalleryImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredefinedGalleryImages();
            return result;
        }
    }
    async getRecentWaivers(): Promise<Array<UnifiedWaiverForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentWaivers();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentWaivers();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSubscriberCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriberCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriberCount();
            return result;
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getTotalCheckIns(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalCheckIns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalCheckIns(arg0);
            return result;
        }
    }
    async getTranslation(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTranslation(arg0);
                return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTranslation(arg0);
            return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWaiversWithVisitCounts(): Promise<Array<UnifiedWaiverForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaiversWithVisitCounts();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaiversWithVisitCounts();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWebsiteContent(): Promise<WebsiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsiteContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsiteContent();
            return result;
        }
    }
    async httpStreamingCallback(arg0: StreamingToken): Promise<StreamingCallbackHttpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.httpStreamingCallback(arg0);
                return from_candid_StreamingCallbackHttpResponse_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.httpStreamingCallback(arg0);
            return from_candid_StreamingCallbackHttpResponse_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async importTranslations(arg0: Array<TranslationEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importTranslations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importTranslations(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllWaivers(): Promise<Array<UnifiedWaiverForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllWaivers();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllWaivers();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async listLanguagePreferences(): Promise<Array<LanguagePreference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLanguagePreferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLanguagePreferences();
            return result;
        }
    }
    async listTranslations(): Promise<Array<TranslationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTranslations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTranslations();
            return result;
        }
    }
    async removeBirthdayPackage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBirthdayPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBirthdayPackage(arg0);
            return result;
        }
    }
    async removeCommunityPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCommunityPost(arg0);
            return result;
        }
    }
    async removeGalleryImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGalleryImage(arg0);
            return result;
        }
    }
    async removeLanguagePreference(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeLanguagePreference();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeLanguagePreference();
            return result;
        }
    }
    async removeTestimonial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTestimonial(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchWaivers(arg0: string): Promise<Array<UnifiedWaiverForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchWaivers(arg0);
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchWaivers(arg0);
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async setLanguagePreference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLanguagePreference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLanguagePreference(arg0);
            return result;
        }
    }
    async submitUnifiedWaiver(arg0: string, arg1: string, arg2: string, arg3: Array<Child>, arg4: boolean, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitUnifiedWaiver(arg0, arg1, arg2, to_candid_vec_n22(this.uploadFile, this.downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitUnifiedWaiver(arg0, arg1, arg2, to_candid_vec_n22(this.uploadFile, this.downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async subscribeEmail(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeEmail(arg0);
            return result;
        }
    }
    async unifiedWaiverSearch(arg0: string): Promise<Array<UnifiedWaiverForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.unifiedWaiverSearch(arg0);
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unifiedWaiverSearch(arg0);
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async updateWebsiteContent(arg0: WebsiteContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWebsiteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWebsiteContent(arg0);
            return result;
        }
    }
}
function from_candid_Child_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Child): Child {
    return from_candid_record_n17(uploadFile, downloadFile, value);
}
function from_candid_HttpResponse_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HttpResponse): HttpResponse {
    return from_candid_record_n4(uploadFile, downloadFile, value);
}
function from_candid_StreamingCallbackHttpResponse_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreamingCallbackHttpResponse): StreamingCallbackHttpResponse {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_StreamingStrategy_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreamingStrategy): StreamingStrategy {
    return from_candid_variant_n7(uploadFile, downloadFile, value);
}
function from_candid_UnifiedWaiverForm_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnifiedWaiverForm): UnifiedWaiverForm {
    return from_candid_record_n14(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(uploadFile, downloadFile, value);
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StreamingToken]): StreamingToken | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StreamingStrategy]): StreamingStrategy | null {
    return value.length === 0 ? null : from_candid_StreamingStrategy_n6(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    frequentVisitors: Array<_UnifiedWaiverForm>;
    totalCheckIns: bigint;
}): {
    frequentVisitors: Array<UnifiedWaiverForm>;
    totalCheckIns: bigint;
} {
    return {
        frequentVisitors: from_candid_vec_n12(uploadFile, downloadFile, value.frequentVisitors),
        totalCheckIns: value.totalCheckIns
    };
}
function from_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    parentEmail: string;
    agreeUnifiedTerms: boolean;
    visitCount: bigint;
    parentPhone: string;
    children: Array<_Child>;
    termsAndConditions: string;
    timestamp: bigint;
    parentName: string;
}): {
    id: string;
    parentEmail: string;
    agreeUnifiedTerms: boolean;
    visitCount: bigint;
    parentPhone: string;
    children: Array<Child>;
    termsAndConditions: string;
    timestamp: bigint;
    parentName: string;
} {
    return {
        id: value.id,
        parentEmail: value.parentEmail,
        agreeUnifiedTerms: value.agreeUnifiedTerms,
        visitCount: value.visitCount,
        parentPhone: value.parentPhone,
        children: from_candid_vec_n15(uploadFile, downloadFile, value.children),
        termsAndConditions: value.termsAndConditions,
        timestamp: value.timestamp,
        parentName: value.parentName
    };
}
function from_candid_record_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    birthday: [] | [string];
}): {
    name: string;
    birthday?: string;
} {
    return {
        name: value.name,
        birthday: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.birthday))
    };
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: [] | [_StreamingToken];
    body: Uint8Array;
}): {
    token?: StreamingToken;
    body: Uint8Array;
} {
    return {
        token: record_opt_to_undefined(from_candid_opt_n21(uploadFile, downloadFile, value.token)),
        body: value.body
    };
}
function from_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    body: Uint8Array;
    headers: Array<_HeaderField>;
    streaming_strategy: [] | [_StreamingStrategy];
    status_code: number;
}): {
    body: Uint8Array;
    headers: Array<HeaderField>;
    streaming_strategy?: StreamingStrategy;
    status_code: number;
} {
    return {
        body: value.body,
        headers: value.headers,
        streaming_strategy: record_opt_to_undefined(from_candid_opt_n5(uploadFile, downloadFile, value.streaming_strategy)),
        status_code: value.status_code
    };
}
function from_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Callback: {
        token: _StreamingToken;
        callback: [Principal, string];
    };
}): {
    __kind__: "Callback";
    Callback: {
        token: StreamingToken;
        callback: [Principal, string];
    };
} {
    return "Callback" in value ? {
        __kind__: "Callback",
        Callback: value.Callback
    } : value;
}
function from_candid_vec_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UnifiedWaiverForm>): Array<UnifiedWaiverForm> {
    return value.map((x)=>from_candid_UnifiedWaiverForm_n13(uploadFile, downloadFile, x));
}
function from_candid_vec_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Child>): Array<Child> {
    return value.map((x)=>from_candid_Child_n16(uploadFile, downloadFile, x));
}
function to_candid_Child_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Child): _Child {
    return to_candid_record_n24(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    birthday?: string;
}): {
    name: string;
    birthday: [] | [string];
} {
    return {
        name: value.name,
        birthday: value.birthday ? candid_some(value.birthday) : candid_none()
    };
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Child>): Array<_Child> {
    return value.map((x)=>to_candid_Child_n23(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
