/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BirthdayPackage {
  'id' : string,
  'additionalChildPrice' : bigint,
  'socksIncluded' : bigint,
  'weekendPrice' : bigint,
  'weekdayPrice' : bigint,
  'name' : string,
  'includedChildren' : bigint,
  'description' : string,
  'roomTime' : string,
}
export interface Child { 'name' : string, 'birthday' : [] | [string] }
export interface CommunityPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
}
export interface ContactSubmission {
  'id' : string,
  'name' : string,
  'numChildren' : bigint,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
  'eventDate' : string,
}
export interface EmailSubscriber { 'email' : string, 'timestamp' : Time }
export interface FileMetadata {
  'path' : string,
  'size' : bigint,
  'mimeType' : string,
}
export interface GalleryImage {
  'id' : string,
  'url' : string,
  'description' : string,
  'timestamp' : bigint,
}
export type HeaderField = [string, string];
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export interface LanguagePreference {
  'userId' : Principal,
  'language' : string,
}
export interface MarketingInfo {
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type StreamingCallback = ActorMethod<
  [StreamingToken],
  StreamingCallbackHttpResponse
>;
export interface StreamingCallbackHttpResponse {
  'token' : [] | [StreamingToken],
  'body' : Uint8Array,
}
export type StreamingStrategy = {
    'Callback' : { 'token' : StreamingToken, 'callback' : [Principal, string] }
  };
export interface StreamingToken { 'resource' : string, 'index' : bigint }
export interface Testimonial {
  'id' : string,
  'customerName' : string,
  'review' : string,
  'timestamp' : bigint,
}
export type Time = bigint;
export interface TranslationEntry {
  'originalText' : string,
  'translatedText' : string,
}
export interface UnifiedWaiverForm {
  'id' : string,
  'parentEmail' : string,
  'agreeUnifiedTerms' : boolean,
  'visitCount' : bigint,
  'parentPhone' : string,
  'children' : Array<Child>,
  'termsAndConditions' : string,
  'timestamp' : bigint,
  'parentName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebsiteContent {
  'homepageText' : string,
  'contactInfo' : string,
  'aboutText' : string,
  'operatingHours' : string,
}
export interface _SERVICE {
  'addBirthdayPackage' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, bigint, string, string],
    undefined
  >,
  'addCommunityPost' : ActorMethod<[string, string, string], undefined>,
  'addContactSubmission' : ActorMethod<
    [string, string, string, string, bigint, string],
    undefined
  >,
  'addGalleryImage' : ActorMethod<[string, string], undefined>,
  'addOrUpdateTranslation' : ActorMethod<[string, string], undefined>,
  'addTestimonial' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkInWaiver' : ActorMethod<[string], bigint>,
  'exportEmailSubscribersCSV' : ActorMethod<[], string>,
  'fileDelete' : ActorMethod<[string], undefined>,
  'fileList' : ActorMethod<[], Array<FileMetadata>>,
  'fileRequest' : ActorMethod<[HttpRequest], HttpResponse>,
  'fileUpload' : ActorMethod<[string, string, Uint8Array, boolean], undefined>,
  'getAllMarketingInfo' : ActorMethod<[], Array<MarketingInfo>>,
  'getBirthdayPackages' : ActorMethod<[], Array<BirthdayPackage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckInStats' : ActorMethod<
    [],
    { 'frequentVisitors' : Array<UnifiedWaiverForm>, 'totalCheckIns' : bigint }
  >,
  'getCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getEmailSubscribers' : ActorMethod<[], Array<EmailSubscriber>>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getLanguagePreference' : ActorMethod<[], [] | [string]>,
  'getNewWaivers' : ActorMethod<[bigint], Array<UnifiedWaiverForm>>,
  'getPredefinedGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getRecentWaivers' : ActorMethod<[], Array<UnifiedWaiverForm>>,
  'getSubscriberCount' : ActorMethod<[], bigint>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTotalCheckIns' : ActorMethod<[string], bigint>,
  'getTranslation' : ActorMethod<[string], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaiversWithVisitCounts' : ActorMethod<[], Array<UnifiedWaiverForm>>,
  'getWebsiteContent' : ActorMethod<[], WebsiteContent>,
  'httpStreamingCallback' : ActorMethod<
    [StreamingToken],
    StreamingCallbackHttpResponse
  >,
  'importTranslations' : ActorMethod<[Array<TranslationEntry>], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllWaivers' : ActorMethod<[], Array<UnifiedWaiverForm>>,
  'listLanguagePreferences' : ActorMethod<[], Array<LanguagePreference>>,
  'listTranslations' : ActorMethod<[], Array<TranslationEntry>>,
  'removeBirthdayPackage' : ActorMethod<[string], undefined>,
  'removeCommunityPost' : ActorMethod<[string], undefined>,
  'removeGalleryImage' : ActorMethod<[string], undefined>,
  'removeLanguagePreference' : ActorMethod<[], undefined>,
  'removeTestimonial' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchWaivers' : ActorMethod<[string], Array<UnifiedWaiverForm>>,
  'setLanguagePreference' : ActorMethod<[string], undefined>,
  'submitUnifiedWaiver' : ActorMethod<
    [string, string, string, Array<Child>, boolean, string],
    string
  >,
  'subscribeEmail' : ActorMethod<[string], boolean>,
  'unifiedWaiverSearch' : ActorMethod<[string], Array<UnifiedWaiverForm>>,
  'updateWebsiteContent' : ActorMethod<[WebsiteContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];